project:
  type: website
  output-dir: docs

website:
  title: "Seahorse website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Res.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full



